package com.vpsmith.rest.addressbook.contact;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping("/contacts")
public class ContactController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ContactRepository contactRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser(@RequestBody Contact)

    )

    {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        ContactEntity n = new ContactEntity();
        n.setName(name);
        n.setEmail(email);
        contactRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<ContactEntity> getAllUsers() {
        // This returns a JSON or XML with the contacts
        return contactRepository.findAll();
    }
}
